export enum TipoGasto {
  ALQUILER = 'ALQUILER',
  AGUA = 'AGUA',
  ELECTRICIDAD = 'ELECTRICIDAD',
  INTERNET = 'INTERNET',
  CREDITO = 'CRÉDITO',
  PUBLICIDAD = 'PUBLICIDAD',
  MONOTRIBUTO = 'MONOTRIBUTO',
  CONTADOR = 'CONTADOR',
  SUELDO_EMPLEADO = 'SUELDO_EMPLEADO',
  OTROS = 'OTROS',
}
